#!/usr/bin/env python3
"""
Applies the reviewed hand edits to a freshly generated cms_v2 migration.
Usage: python3 scripts/cms/patch-cms-v2-migration.py migrations/<timestamp>_cms_v2.ts

Kept in the repo so the edits are reproducible and reviewable.
"""
import sys

path = sys.argv[1]
s = open(path).read()
i = s.index('export async function down')
up, down = s[:i], s[i:]

def once(text, old, new, where):
    assert text.count(old) == 1, f'{where}: expected exactly one match for {old!r}'
    return text.replace(old, new)

# up: preserve user access — admins become super-admins, "viewer" retires.
a = """  ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'editor'::text;\n"""
up = once(up, a, a + """  -- [data] roles: the existing admin(s) become super-admin so user management
  -- is not locked out; the retired "viewer" role maps to the least-privileged role.
  UPDATE "users" SET "role" = 'super-admin' WHERE "role" = 'admin';
  UPDATE "users" SET "role" = 'author' WHERE "role" = 'viewer';
""", 'up/roles')

# up: move services.meta_description into the SEO group before the drop.
b = '  ALTER TABLE "services" DROP COLUMN "meta_description";\n'
up = once(up, b, """  -- [data] services: move the meta description into the shared SEO group before dropping it.
  UPDATE "services" SET "seo_meta_description" = "meta_description" WHERE "seo_meta_description" IS NULL;
""" + b, 'up/meta')

# down: reverse the data mapping so a rollback works.
c = """  ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'editor'::text;\n  DROP TYPE "public"."enum_users_role";\n  CREATE TYPE "public"."enum_users_role" AS ENUM('admin', 'editor', 'viewer');"""
down = once(down, c, """  ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'editor'::text;
  UPDATE "users" SET "role" = 'admin' WHERE "role" IN ('super-admin', 'admin');
  UPDATE "users" SET "role" = 'viewer' WHERE "role" = 'author';
  DROP TYPE "public"."enum_users_role";
  CREATE TYPE "public"."enum_users_role" AS ENUM('admin', 'editor', 'viewer');""", 'down/roles')
d = '  ALTER TABLE "services" ADD COLUMN "meta_description" varchar NOT NULL;\n'
down = once(down, d, '  ALTER TABLE "services" ADD COLUMN "meta_description" varchar;\n', 'down/meta-add')
e = '  ALTER TABLE "services" DROP COLUMN "seo_meta_description";\n'
down = once(down, e, """  UPDATE "services" SET "meta_description" = COALESCE("seo_meta_description", '');
  ALTER TABLE "services" ALTER COLUMN "meta_description" SET NOT NULL;
""" + e, 'down/meta-copy')
# drizzle-kit drops FKs after CASCADE already removed them — make drops idempotent.
down = (down.replace('DROP CONSTRAINT "', 'DROP CONSTRAINT IF EXISTS "')
            .replace('DROP INDEX "', 'DROP INDEX IF EXISTS "')
            .replace('DROP COLUMN "', 'DROP COLUMN IF EXISTS "'))

header = '''/**
 * CMS v2 — production content model. Generated by `payload migrate:create`,
 * then patched by scripts/cms/patch-cms-v2-migration.py (reviewed by hand).
 *
 * Destructive statements and why they are safe (production inventory taken
 * read-only on 2026-09-27):
 *  - DROP COLUMN on *_id upload columns (cover/avatar/logo/og/image) — every
 *    one was NULL in production; replaced by the image group (upload OR URL + alt).
 *  - DROP COLUMN services.meta_description — copied to seo_meta_description first.
 *  - DROP COLUMN blog_posts.status — the legacy custom status select, superseded
 *    by Payload's own _status (it also collided with that enum's name). Its values
 *    were a copy of the repo's content files; the seed script re-applies them.
 *  - DROP COLUMN pillars/industries seo_title, seo_canonical_override,
 *    blog_posts.pillar_link_id, redirects.permanent — NULL / empty table.
 *  - DROP COLUMN projects_gallery.caption — gallery tables were empty.
 *  - enum_users_role rebuilt: admin → super-admin, viewer → author.
 *
 * No table is dropped. Payload runs the whole migration in one transaction.
 */
'''
s = up.replace('import { MigrateUpArgs', header + 'import { MigrateUpArgs', 1) + down
open(path, 'w').write(s)
print('patched', path)
